CREATE TABLE IF NOT EXISTS categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL
);

ALTER TABLE products 
  ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]'::jsonb, 
  ADD COLUMN IF NOT EXISTS category_id TEXT REFERENCES categories(id);
