import path from "node:path";
import { promises as fs } from "node:fs";

type PlannerItem = Record<string, unknown> & {
  id: string;
  category?: string;
  plannerPhase?: string;
};

type RuntimeCandidatePayload = {
  items?: PlannerItem[];
};

function toText(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function toNumber(value: unknown, fieldName: string, itemId: string): number {
  const numericValue =
    typeof value === "number"
      ? value
      : typeof value === "string"
        ? Number(value)
        : Number.NaN;

  if (!Number.isFinite(numericValue)) {
    throw new Error(`Invalid numeric field "${fieldName}" for planner runtime item "${itemId}".`);
  }

  return numericValue;
}

function validateRuntimeItems(items: PlannerItem[]) {
  const uniqueIds = new Set<string>();

  return items.map((item, index) => {
    const id = toText(item.id);
    const name = toText(item.name);
    const category = toText(item.category);
    const plannerPhase = toText(item.plannerPhase);

    if (!id || !name || !category || !plannerPhase) {
      throw new Error(
        `Planner runtime item ${index + 1} is missing id, name, category, or plannerPhase.`,
      );
    }

    if (uniqueIds.has(id)) {
      throw new Error(`Duplicate planner runtime item id found: "${id}".`);
    }

    uniqueIds.add(id);

    return {
      ...item,
      id,
      name,
      category,
      plannerPhase,
      width: toNumber(item.width, "width", id),
      depth: toNumber(item.depth, "depth", id),
      height: toNumber(item.height, "height", id),
    };
  });
}

async function writeFile(filePath: string, contents: string) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, contents, "utf8");
}

async function main() {
  const rootDir = process.cwd();
  const runtimeCandidatePath = path.join(rootDir, "output", "planner-runtime-candidate.json");
  const generatedJsPath = path.join(rootDir, "public", "planner-app", "planner-catalog.generated.js");
  const generatedJsonPath = path.join(rootDir, "public", "planner-app", "data", "planner-catalog.v1.json");
  const manifestPath = path.join(rootDir, "public", "planner-app", "data", "planner-catalog.manifest.json");

  const payload = JSON.parse(
    await fs.readFile(runtimeCandidatePath, "utf8"),
  ) as RuntimeCandidatePayload;
  const items = validateRuntimeItems(Array.isArray(payload.items) ? payload.items : []);
  const generatedAt = new Date().toISOString();
  const manifest = {
    version: "v1",
    generatedAt,
    source: "output/planner-runtime-candidate.json",
    itemCount: items.length,
    categoryCount: [...new Set(items.map((item) => String(item.category || "")))].filter(Boolean).length,
    phaseOneItemCount: items.filter((item) => item.plannerPhase === "phase-1-office").length,
  };

  await writeFile(
    generatedJsonPath,
    `${JSON.stringify({ ...manifest, items }, null, 2)}\n`,
  );

  await writeFile(
    manifestPath,
    `${JSON.stringify(manifest, null, 2)}\n`,
  );

  await writeFile(
    generatedJsPath,
    `// Generated by scripts/publish-planner-runtime-candidate.ts\n(function () {\n  window.furnitureLibrary = ${JSON.stringify(items, null, 2)};\n  window.furnitureLibraryMeta = ${JSON.stringify(manifest, null, 2)};\n})();\n`,
  );

  console.log(
    `Published planner runtime candidate with ${items.length} items across ${manifest.categoryCount} categories.`,
  );
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`[planner:runtime:publish] ${message}`);
  process.exitCode = 1;
});
